import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Toaster } from "@/components/ui/toaster";

const OutfitSans = Outfit({
  variable: "--font--outfit--sans",
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Smart-Notes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        suppressHydrationWarning>
        <body
          className={`${OutfitSans.variable} antialiased overflow-x-hidden`}>
          <Provider>
            {children}
            <Toaster />
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
