export const metadata = {
  title: "Study Notes | StudyMate AI",
  description:
    "Access detailed study notes and chapter content generated by AI for your learning journey",
  keywords:
    "study notes, chapter content, AI-generated notes, learning materials, education",
};

export default function NotesLayout({ children }) {
  return <div className="min-h-screen bg-background">{children}</div>;
}
